### ISSUE TITLE
Add `--zip` flag to the build command

### ISSUE THREAD

**Issue by calavera** [calavera/cargo-lambda#3]
Add a `--zip` flag to the build command to generated compressed files ready to upload to lambda.

**Comment by messense** [comment]
IMO, `--zip` should be the default behavior? Then a `--no-zip` flag should be added to disable it.

**Comment by DeveloperC286** [comment]
https://github.com/calavera/cargo-lambda/pull/10 closes this issue.

I went the approach of an enum rather than a boolean flag, they are more extensible.

E.g. AWS Lambda current supports OCI images, possibly in the future cargo-lambda may want to output Docker images or something...

**Comment by calavera** [comment]
Fixed.
