### ISSUE TITLE
Check if the target toolchain is installed before building, and install it if it's missing

### ISSUE THREAD

**Issue by calavera** [calavera/cargo-lambda#30]
When you run `cargo lambda build --target ...`, it'd be interesting to check if the toolchain is already installed, and install it if it's not installed.

We could also validate that the flag value is one of the only two toolchains that lambda supports.

**Comment by rnag** [comment]
this is just a personal preference, but I'd probably see if there's a way to limit calling `rustup target list --installed` on each run, perhaps by caching a list of installed targets somewhere; at least on my mac, calling `rustup` to determine a list of targets seems to be a somewhat expensive operation.

as an alternate option, I found that you can use `ls` to get a list of directory names in the `$RUSTUP_HOME` folder, which should basically indicate which targets are installed for the current toolchain being used by `cargo`; this seems to work on a Mac/Linux environment anyway, haven't tested on windows yet.

```
$RUSTUP_HOME/toolchains/$CURRENT_TOOLCHAIN/lib/rustlib
```

For example, on my mac the full path which lists the targets for the default toolchain, would look like: `~/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib`

**Comment by calavera** [comment]
it might not be worth the effort. Rust developers are usually used to working with targets and toolchains, so it might not be necessary.
