### ISSUE TITLE
Running Without `cargo-watch`

### ISSUE THREAD

**Issue by indiv0** [calavera/cargo-lambda#54]
Hi! This is an awesome project!

Would it be possible to add a "no cargo-watch" mode? That is, just a standalone `cargo lambda` server without the auto-rebuild? I'd like to use the emulated Lambda control plane in integration tests but it's tricky to do so when the server is tracking file changes.

**Comment by calavera** [comment]
That's an interesting suggestion. I didn't really think about this use case. Feel free to open a Pull Request with changes to support that option.

**Comment by calavera** [comment]
Fixed in #55

I'll release a new version tomorrow with this new flag in it. Thanks @rainDelay9 for your help! 🎊
